version: "3"
services:
  nginx-snowplow:
    build:
      context: ./
      dockerfile: Dockerfile
    image: nginx-snowplow:latest
    container_name: nginx-snowplow
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"